# Generated by Django 2.1.7 on 2020-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_merge_20191204_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_registration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[('active', 1), ('blocked', 2), ('not_activated', 3)], default=3, verbose_name='Статус'),
        ),
    ]
