# Generated by Django 2.1.7 on 2020-09-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20191224_2306'),
        ('website', '0013_auto_20200912_1134'),
    ]

    operations = [
    ]
