# Generated by Django 2.1.7 on 2020-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200912_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='estimate',
            field=models.IntegerField(choices=[('dislike', 1), ('like', 2)], default=2, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='requestforpublication',
            name='status',
            field=models.IntegerField(choices=[('new', 1), ('rejected', 2), ('published', 3), ('rejected_forever', 4)], default=1, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='requestupdatestatus',
            name='status',
            field=models.IntegerField(choices=[('new', 1), ('rejected', 2), ('published', 3), ('rejected_forever', 4)], default=1, verbose_name='Статус обновления уровня профиля'),
        ),
    ]
